@extends('layouts.template')
@section('layout_content')
<h2>Please Contact Us</h2>
<table>
    <tr>
            <td>
                phone
            </td>
            <td>
                08123192319
            </td>
        </tr>
        <tr>
            <td>
                email
            </td>
            <td>
                abc@gmail.com
            </td>
        </tr>
        <tr>
            <td>
                address
            </td>
            <td>
                main st. 91
            </td>
        </tr>
    </table>
@endsection